services:
  - type: web
    name: villageconnect-backend
    runtime: docker
    plan: free
    region: singapore
    branch: main
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-dry-base-ay243bi3.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_8oHlT1qupmLt
      - key: JWT_SECRET
        value: villageconnect_super_secret_key_2024_make_it_very_long_and_secure
